name: Build and test
on: [push, pull_request]
jobs:
  test:
    if: |
      !startsWith(github.ref, 'refs/tags')
    name: Generate build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: npm install
      - run: npm run build-all
