name: Build
on: [push, pull_request]
jobs:
  build:
    if: !startsWith(github.ref, 'refs/tags')
    name: Generate build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: |
          npm install
          npm run build-all