on:
  push:
    tags:
      - '*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Build
        run: |
          npm install
          npm run build-all
          cd dist/chrome
          zip -r ../chrome.zip *
          cd ../edge
          zip -r ../edge.zip *
          cd ../firefox
          zip -r ../firefox.zip *
          cd ../opera
          zip -r ../opera.zip *
          cd ../..
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./dist/chrome.zip
            ./dist/edge.zip
            ./dist/firefox.zip
            ./dist/opera.zip
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false